import torch
import torch.nn as nn
import torch.nn.functional as F

from reskill.models.helpers import SinusoidalPosEmb

class FlowTeacher(nn.Module):
    """
    cond = [s0, noisy_a0]
    s0: state dim
    noisy_a0: action dim
    z: latent dim
    """
    
    def __init__(self, cond_dim, latent_dim, hidden_dim, time_dim, device):
        super().__init__()
        self.cond_dim = cond_dim
        self.latent_dim = latent_dim
        self.hidden_dim = hidden_dim
        self.time_dim = time_dim
        self.device = device
        
        self.time_mlp = nn.Sequential(
            SinusoidalPosEmb(time_dim),
            nn.Linear(time_dim, time_dim * 2),
            nn.Mish(),
            nn.Linear(time_dim * 2, time_dim)
        )
        
        input_dim = cond_dim + latent_dim + time_dim
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.Mish(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.Mish(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.Mish(),
            nn.Linear(hidden_dim, latent_dim)
        )
        
    def forward(self, cond, z_t, t):
        if t.dim() == 2 and t.shape[1] == 1:
            t = t.squeeze(1)
            
        t_emb = self.time_mlp(t)
        x = torch.cat([cond, z_t, t_emb], dim=1)
        return self.net(x)
    
class FlowStudent(nn.Module):
    """
    cond = [o, n]
    noise -> z: latent dim
    """
    
    def __init__(self, cond_dim, latent_dim, hidden_dim, device):
        super().__init__()
        self.cond_dim = cond_dim
        self.latent_dim = latent_dim
        self.hidden_dim = hidden_dim
        self.device = device
        
        input_dim = cond_dim + latent_dim
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.Mish(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.Mish(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.Mish(),
            nn.Linear(hidden_dim, latent_dim)
        )
    
    def forward(self, cond, noise):
        x = torch.cat([cond, noise], dim=1)
        return self.net(x)
    
def compute_flow_loss(flow_teacher, cond, target_z, sample_weight=None, eps=1e-8):
    """
    flow_teacher: teacher model
    cond: [o, n], size: [B, cond_dim]
    target_z: z* generated by SkillVAE, size: [B, latent_dim]
    """
    
    batch_size = target_z.shape[0]
    latent_dim = target_z.shape[1]
    x_0 = torch.randn(batch_size, latent_dim, device=target_z.device, dtype=target_z.dtype)
    x_1 = target_z
    t = torch.rand(batch_size, 1, device=target_z.device, dtype=target_z.dtype)
    x_t = x_0 * (1 - t) + x_1 * t
    
    vel = x_1 - x_0
    pred = flow_teacher(cond, x_t, t)
    per_sample_loss = F.mse_loss(pred, vel, reduction="none").mean(dim=1)
    if sample_weight is not None:
        sample_weight = sample_weight.to(device=target_z.device, dtype=target_z.dtype).view(-1)
        loss = (per_sample_loss * sample_weight).sum() / (sample_weight.sum() + eps)
    else:
        loss = per_sample_loss.mean()
    
    stats = {
        "t": t.detach(),
        "z_t": x_t.detach(),
        "target_vel": vel.detach(),
        "pred_vel": pred.detach(),
        "per_sample_loss": per_sample_loss.detach()
    }
   
    return loss, stats

@torch.no_grad()
def compute_flow_z(flow_teacher, cond, noises, flow_steps, max_action):
    batch_size = cond.shape[0]
    z = noises
    dt = 1.0 / float(flow_steps)
    
    for i in range(flow_steps):
        t = torch.full((batch_size, 1), float(i) / float(flow_steps), device=cond.device, dtype=cond.dtype)
        vel = flow_teacher(cond, z, t)
        z = z + dt * vel
        z = z.clamp(-max_action, max_action)
    
    return z

def compute_flow_z_guided(flow_teacher, cond, noises, flow_steps, max_action, q_fn, n_obs, guidance_scale=0.0, grad_clip=0.0):
    batch_size = cond.shape[0]
    z = noises
    dt = 1.0 / float(flow_steps)
    obs = cond[:, :n_obs].detach()
    
    for i in range(flow_steps):
        t = torch.full((batch_size, 1), float(i) / float(flow_steps), device=cond.device, dtype=cond.dtype)
        
        with torch.no_grad():
            vel = flow_teacher(cond, z, t)
        
        with torch.enable_grad():
            z_in = z.detach().requires_grad_(True)
            q_value = q_fn(torch.cat([obs, z_in], dim=1)).reshape(-1, 1)
            grad = torch.autograd.grad(q_value.sum(), z_in)[0].float()
        
        if grad_clip is not None and grad_clip > 0:
            grad_norm = grad.norm(dim=1, keepdim=True).clamp_min(1e-6)
            grad = grad * (grad_clip / grad_norm).clamp(max=1.0)
        
        z = z + dt * (vel + guidance_scale * grad)
        z = z.clamp(-max_action, max_action)
    
    return z

def compute_distill_loss(flow_teacher, flow_student, cond, flow_steps, max_action):
    batch_size = cond.shape[0]
    latent_dim = flow_teacher.latent_dim    
    noises = torch.randn(batch_size, latent_dim, device=cond.device, dtype=cond.dtype)
    
    with torch.no_grad():
        target_teacher = compute_flow_z(flow_teacher, cond, noises, flow_steps, max_action)
        
    pred_student = flow_student(cond, noises)
    loss = F.mse_loss(pred_student, target_teacher)
    
    stats = {
        "target_teacher": target_teacher.detach(),
        "pred_student": pred_student.detach()
    }
    
    return loss, stats
