#!/usr/bin/env bash

gpu=1
seeds=(2)

pick=500
push=1
dataset_name=fetch_block_push1_pick500_labeled_flowbeh_beta02_wmin01_wmax300

use_grad=1
guidance_scale=0.1
guidance_warmup_epoch=1
guidance_grad_clip=10.0

max_residual_factor=1
use_condition_flow=1

condition_use_grad=1
# condition_guidance_scale=1
condition_guidance_scale=$guidance_scale
condition_guidance_warmup_epoch=1
condition_guidance_grad_clip=10.0

chunk_critic_ensembles=1
chunk_critic_hidden_dim=256
chunk_critic_hidden_layers=2
chunk_critic_activation=tanh
chunk_critic_lr=0.0003
chunk_critic_tau=0.005
chunk_critic_batch_size=512
chunk_critic_updates_per_epoch=180
chunk_critic_replay_size=600000

condition_critic_ensembles=$chunk_critic_ensembles
condition_critic_hidden_dim=$chunk_critic_hidden_dim
condition_critic_hidden_layers=$chunk_critic_hidden_layers
condition_critic_activation=$chunk_critic_activation
condition_critic_lr=$chunk_critic_lr
condition_critic_tau=$chunk_critic_tau
condition_critic_batch_size=$chunk_critic_batch_size
condition_critic_updates_per_epoch=$chunk_critic_updates_per_epoch
condition_critic_replay_size=$chunk_critic_replay_size

environment_name=slippery_push
swanlab_project=Flow_skill_1_${environment_name}
log_subdir=newPara
run_name=condflow${use_condition_flow}_condgrad${condition_use_grad}_${dataset_name}_qz${guidance_scale}_qc${condition_guidance_scale}_cgwarm${condition_guidance_warmup_epoch}_newPara_off-policy_rawgrad
